// Copyright 2022-2023 Buf Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: buf/javamultiplefiles/disabled/v1/disabled_empty.proto

package buf.javamultiplefiles.disabled.v1;

public final class DisabledEmptyOuterClass {
  private DisabledEmptyOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DisabledEmptyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:buf.javamultiplefiles.disabled.v1.DisabledEmpty)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code buf.javamultiplefiles.disabled.v1.DisabledEmpty}
   */
  public static final class DisabledEmpty extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:buf.javamultiplefiles.disabled.v1.DisabledEmpty)
      DisabledEmptyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DisabledEmpty.newBuilder() to construct.
    private DisabledEmpty(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DisabledEmpty() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DisabledEmpty();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DisabledEmpty(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.internal_static_buf_javamultiplefiles_disabled_v1_DisabledEmpty_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.internal_static_buf_javamultiplefiles_disabled_v1_DisabledEmpty_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmpty.class, buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmpty.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmpty)) {
        return super.equals(obj);
      }
      buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmpty other = (buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmpty) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmpty parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmpty parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmpty parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmpty parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmpty parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmpty parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmpty parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmpty parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmpty parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmpty parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmpty parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmpty parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmpty prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code buf.javamultiplefiles.disabled.v1.DisabledEmpty}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:buf.javamultiplefiles.disabled.v1.DisabledEmpty)
        buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.internal_static_buf_javamultiplefiles_disabled_v1_DisabledEmpty_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.internal_static_buf_javamultiplefiles_disabled_v1_DisabledEmpty_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmpty.class, buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmpty.Builder.class);
      }

      // Construct using buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmpty.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.internal_static_buf_javamultiplefiles_disabled_v1_DisabledEmpty_descriptor;
      }

      @java.lang.Override
      public buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmpty getDefaultInstanceForType() {
        return buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmpty.getDefaultInstance();
      }

      @java.lang.Override
      public buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmpty build() {
        buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmpty result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmpty buildPartial() {
        buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmpty result = new buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmpty(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmpty) {
          return mergeFrom((buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmpty)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmpty other) {
        if (other == buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmpty.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmpty parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmpty) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:buf.javamultiplefiles.disabled.v1.DisabledEmpty)
    }

    // @@protoc_insertion_point(class_scope:buf.javamultiplefiles.disabled.v1.DisabledEmpty)
    private static final buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmpty DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmpty();
    }

    public static buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmpty getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DisabledEmpty>
        PARSER = new com.google.protobuf.AbstractParser<DisabledEmpty>() {
      @java.lang.Override
      public DisabledEmpty parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DisabledEmpty(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DisabledEmpty> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DisabledEmpty> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmpty getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DisabledEmptyRPCRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:buf.javamultiplefiles.disabled.v1.DisabledEmptyRPCRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code buf.javamultiplefiles.disabled.v1.DisabledEmptyRPCRequest}
   */
  public static final class DisabledEmptyRPCRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:buf.javamultiplefiles.disabled.v1.DisabledEmptyRPCRequest)
      DisabledEmptyRPCRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DisabledEmptyRPCRequest.newBuilder() to construct.
    private DisabledEmptyRPCRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DisabledEmptyRPCRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DisabledEmptyRPCRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DisabledEmptyRPCRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.internal_static_buf_javamultiplefiles_disabled_v1_DisabledEmptyRPCRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.internal_static_buf_javamultiplefiles_disabled_v1_DisabledEmptyRPCRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCRequest.class, buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCRequest.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCRequest)) {
        return super.equals(obj);
      }
      buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCRequest other = (buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCRequest) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code buf.javamultiplefiles.disabled.v1.DisabledEmptyRPCRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:buf.javamultiplefiles.disabled.v1.DisabledEmptyRPCRequest)
        buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.internal_static_buf_javamultiplefiles_disabled_v1_DisabledEmptyRPCRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.internal_static_buf_javamultiplefiles_disabled_v1_DisabledEmptyRPCRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCRequest.class, buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCRequest.Builder.class);
      }

      // Construct using buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.internal_static_buf_javamultiplefiles_disabled_v1_DisabledEmptyRPCRequest_descriptor;
      }

      @java.lang.Override
      public buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCRequest getDefaultInstanceForType() {
        return buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCRequest.getDefaultInstance();
      }

      @java.lang.Override
      public buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCRequest build() {
        buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCRequest buildPartial() {
        buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCRequest result = new buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCRequest(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCRequest) {
          return mergeFrom((buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCRequest other) {
        if (other == buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:buf.javamultiplefiles.disabled.v1.DisabledEmptyRPCRequest)
    }

    // @@protoc_insertion_point(class_scope:buf.javamultiplefiles.disabled.v1.DisabledEmptyRPCRequest)
    private static final buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCRequest();
    }

    public static buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DisabledEmptyRPCRequest>
        PARSER = new com.google.protobuf.AbstractParser<DisabledEmptyRPCRequest>() {
      @java.lang.Override
      public DisabledEmptyRPCRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DisabledEmptyRPCRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DisabledEmptyRPCRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DisabledEmptyRPCRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DisabledEmptyRPCResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:buf.javamultiplefiles.disabled.v1.DisabledEmptyRPCResponse)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code buf.javamultiplefiles.disabled.v1.DisabledEmptyRPCResponse}
   */
  public static final class DisabledEmptyRPCResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:buf.javamultiplefiles.disabled.v1.DisabledEmptyRPCResponse)
      DisabledEmptyRPCResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DisabledEmptyRPCResponse.newBuilder() to construct.
    private DisabledEmptyRPCResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DisabledEmptyRPCResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DisabledEmptyRPCResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DisabledEmptyRPCResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.internal_static_buf_javamultiplefiles_disabled_v1_DisabledEmptyRPCResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.internal_static_buf_javamultiplefiles_disabled_v1_DisabledEmptyRPCResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCResponse.class, buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCResponse.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCResponse)) {
        return super.equals(obj);
      }
      buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCResponse other = (buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCResponse) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code buf.javamultiplefiles.disabled.v1.DisabledEmptyRPCResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:buf.javamultiplefiles.disabled.v1.DisabledEmptyRPCResponse)
        buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.internal_static_buf_javamultiplefiles_disabled_v1_DisabledEmptyRPCResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.internal_static_buf_javamultiplefiles_disabled_v1_DisabledEmptyRPCResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCResponse.class, buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCResponse.Builder.class);
      }

      // Construct using buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.internal_static_buf_javamultiplefiles_disabled_v1_DisabledEmptyRPCResponse_descriptor;
      }

      @java.lang.Override
      public buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCResponse getDefaultInstanceForType() {
        return buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCResponse.getDefaultInstance();
      }

      @java.lang.Override
      public buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCResponse build() {
        buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCResponse buildPartial() {
        buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCResponse result = new buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCResponse(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCResponse) {
          return mergeFrom((buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCResponse other) {
        if (other == buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCResponse.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:buf.javamultiplefiles.disabled.v1.DisabledEmptyRPCResponse)
    }

    // @@protoc_insertion_point(class_scope:buf.javamultiplefiles.disabled.v1.DisabledEmptyRPCResponse)
    private static final buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCResponse();
    }

    public static buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DisabledEmptyRPCResponse>
        PARSER = new com.google.protobuf.AbstractParser<DisabledEmptyRPCResponse>() {
      @java.lang.Override
      public DisabledEmptyRPCResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DisabledEmptyRPCResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DisabledEmptyRPCResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DisabledEmptyRPCResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public buf.javamultiplefiles.disabled.v1.DisabledEmptyOuterClass.DisabledEmptyRPCResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_buf_javamultiplefiles_disabled_v1_DisabledEmpty_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_buf_javamultiplefiles_disabled_v1_DisabledEmpty_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_buf_javamultiplefiles_disabled_v1_DisabledEmptyRPCRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_buf_javamultiplefiles_disabled_v1_DisabledEmptyRPCRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_buf_javamultiplefiles_disabled_v1_DisabledEmptyRPCResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_buf_javamultiplefiles_disabled_v1_DisabledEmptyRPCResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n6buf/javamultiplefiles/disabled/v1/disa" +
      "bled_empty.proto\022!buf.javamultiplefiles." +
      "disabled.v1\"\017\n\rDisabledEmpty\"\031\n\027Disabled" +
      "EmptyRPCRequest\"\032\n\030DisabledEmptyRPCRespo" +
      "nse2\244\001\n\024DisabledEmptyService\022\213\001\n\020Disable" +
      "dEmptyRPC\022:.buf.javamultiplefiles.disabl" +
      "ed.v1.DisabledEmptyRPCRequest\032;.buf.java" +
      "multiplefiles.disabled.v1.DisabledEmptyR" +
      "PCResponseB\002P\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_buf_javamultiplefiles_disabled_v1_DisabledEmpty_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_buf_javamultiplefiles_disabled_v1_DisabledEmpty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_buf_javamultiplefiles_disabled_v1_DisabledEmpty_descriptor,
        new java.lang.String[] { });
    internal_static_buf_javamultiplefiles_disabled_v1_DisabledEmptyRPCRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_buf_javamultiplefiles_disabled_v1_DisabledEmptyRPCRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_buf_javamultiplefiles_disabled_v1_DisabledEmptyRPCRequest_descriptor,
        new java.lang.String[] { });
    internal_static_buf_javamultiplefiles_disabled_v1_DisabledEmptyRPCResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_buf_javamultiplefiles_disabled_v1_DisabledEmptyRPCResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_buf_javamultiplefiles_disabled_v1_DisabledEmptyRPCResponse_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
