// Copyright 2022-2023 Buf Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: buf/javamultiplefiles/disabled/v1/disabled_nested.proto

package buf.javamultiplefiles.disabled.v1;

public final class DisabledNested {
  private DisabledNested() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DisabledOuterMessageNestedOrBuilder extends
      // @@protoc_insertion_point(interface_extends:buf.javamultiplefiles.disabled.v1.DisabledOuterMessageNested)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code buf.javamultiplefiles.disabled.v1.DisabledOuterMessageNested}
   */
  public static final class DisabledOuterMessageNested extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:buf.javamultiplefiles.disabled.v1.DisabledOuterMessageNested)
      DisabledOuterMessageNestedOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DisabledOuterMessageNested.newBuilder() to construct.
    private DisabledOuterMessageNested(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DisabledOuterMessageNested() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DisabledOuterMessageNested();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DisabledOuterMessageNested(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return buf.javamultiplefiles.disabled.v1.DisabledNested.internal_static_buf_javamultiplefiles_disabled_v1_DisabledOuterMessageNested_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return buf.javamultiplefiles.disabled.v1.DisabledNested.internal_static_buf_javamultiplefiles_disabled_v1_DisabledOuterMessageNested_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested.class, buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested.Builder.class);
    }

    public interface InnerMessageOrBuilder extends
        // @@protoc_insertion_point(interface_extends:buf.javamultiplefiles.disabled.v1.DisabledOuterMessageNested.InnerMessage)
        com.google.protobuf.MessageOrBuilder {
    }
    /**
     * Protobuf type {@code buf.javamultiplefiles.disabled.v1.DisabledOuterMessageNested.InnerMessage}
     */
    public static final class InnerMessage extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:buf.javamultiplefiles.disabled.v1.DisabledOuterMessageNested.InnerMessage)
        InnerMessageOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use InnerMessage.newBuilder() to construct.
      private InnerMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private InnerMessage() {
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new InnerMessage();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private InnerMessage(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return buf.javamultiplefiles.disabled.v1.DisabledNested.internal_static_buf_javamultiplefiles_disabled_v1_DisabledOuterMessageNested_InnerMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return buf.javamultiplefiles.disabled.v1.DisabledNested.internal_static_buf_javamultiplefiles_disabled_v1_DisabledOuterMessageNested_InnerMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested.InnerMessage.class, buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested.InnerMessage.Builder.class);
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested.InnerMessage)) {
          return super.equals(obj);
        }
        buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested.InnerMessage other = (buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested.InnerMessage) obj;

        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested.InnerMessage parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested.InnerMessage parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested.InnerMessage parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested.InnerMessage parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested.InnerMessage parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested.InnerMessage parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested.InnerMessage parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested.InnerMessage parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested.InnerMessage parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested.InnerMessage parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested.InnerMessage parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested.InnerMessage parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested.InnerMessage prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code buf.javamultiplefiles.disabled.v1.DisabledOuterMessageNested.InnerMessage}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:buf.javamultiplefiles.disabled.v1.DisabledOuterMessageNested.InnerMessage)
          buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested.InnerMessageOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return buf.javamultiplefiles.disabled.v1.DisabledNested.internal_static_buf_javamultiplefiles_disabled_v1_DisabledOuterMessageNested_InnerMessage_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return buf.javamultiplefiles.disabled.v1.DisabledNested.internal_static_buf_javamultiplefiles_disabled_v1_DisabledOuterMessageNested_InnerMessage_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested.InnerMessage.class, buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested.InnerMessage.Builder.class);
        }

        // Construct using buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested.InnerMessage.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return buf.javamultiplefiles.disabled.v1.DisabledNested.internal_static_buf_javamultiplefiles_disabled_v1_DisabledOuterMessageNested_InnerMessage_descriptor;
        }

        @java.lang.Override
        public buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested.InnerMessage getDefaultInstanceForType() {
          return buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested.InnerMessage.getDefaultInstance();
        }

        @java.lang.Override
        public buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested.InnerMessage build() {
          buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested.InnerMessage result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested.InnerMessage buildPartial() {
          buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested.InnerMessage result = new buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested.InnerMessage(this);
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested.InnerMessage) {
            return mergeFrom((buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested.InnerMessage)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested.InnerMessage other) {
          if (other == buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested.InnerMessage.getDefaultInstance()) return this;
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested.InnerMessage parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested.InnerMessage) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:buf.javamultiplefiles.disabled.v1.DisabledOuterMessageNested.InnerMessage)
      }

      // @@protoc_insertion_point(class_scope:buf.javamultiplefiles.disabled.v1.DisabledOuterMessageNested.InnerMessage)
      private static final buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested.InnerMessage DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested.InnerMessage();
      }

      public static buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested.InnerMessage getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<InnerMessage>
          PARSER = new com.google.protobuf.AbstractParser<InnerMessage>() {
        @java.lang.Override
        public InnerMessage parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new InnerMessage(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<InnerMessage> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<InnerMessage> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested.InnerMessage getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested)) {
        return super.equals(obj);
      }
      buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested other = (buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code buf.javamultiplefiles.disabled.v1.DisabledOuterMessageNested}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:buf.javamultiplefiles.disabled.v1.DisabledOuterMessageNested)
        buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNestedOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return buf.javamultiplefiles.disabled.v1.DisabledNested.internal_static_buf_javamultiplefiles_disabled_v1_DisabledOuterMessageNested_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return buf.javamultiplefiles.disabled.v1.DisabledNested.internal_static_buf_javamultiplefiles_disabled_v1_DisabledOuterMessageNested_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested.class, buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested.Builder.class);
      }

      // Construct using buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return buf.javamultiplefiles.disabled.v1.DisabledNested.internal_static_buf_javamultiplefiles_disabled_v1_DisabledOuterMessageNested_descriptor;
      }

      @java.lang.Override
      public buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested getDefaultInstanceForType() {
        return buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested.getDefaultInstance();
      }

      @java.lang.Override
      public buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested build() {
        buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested buildPartial() {
        buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested result = new buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested) {
          return mergeFrom((buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested other) {
        if (other == buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:buf.javamultiplefiles.disabled.v1.DisabledOuterMessageNested)
    }

    // @@protoc_insertion_point(class_scope:buf.javamultiplefiles.disabled.v1.DisabledOuterMessageNested)
    private static final buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested();
    }

    public static buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DisabledOuterMessageNested>
        PARSER = new com.google.protobuf.AbstractParser<DisabledOuterMessageNested>() {
      @java.lang.Override
      public DisabledOuterMessageNested parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DisabledOuterMessageNested(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DisabledOuterMessageNested> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DisabledOuterMessageNested> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public buf.javamultiplefiles.disabled.v1.DisabledNested.DisabledOuterMessageNested getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_buf_javamultiplefiles_disabled_v1_DisabledOuterMessageNested_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_buf_javamultiplefiles_disabled_v1_DisabledOuterMessageNested_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_buf_javamultiplefiles_disabled_v1_DisabledOuterMessageNested_InnerMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_buf_javamultiplefiles_disabled_v1_DisabledOuterMessageNested_InnerMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n7buf/javamultiplefiles/disabled/v1/disa" +
      "bled_nested.proto\022!buf.javamultiplefiles" +
      ".disabled.v1\",\n\032DisabledOuterMessageNest" +
      "ed\032\016\n\014InnerMessage2\321\001\n\033DisabledInnerMess" +
      "ageService\022\261\001\n\027DisabledInnerMessageRPC\022J" +
      ".buf.javamultiplefiles.disabled.v1.Disab" +
      "ledOuterMessageNested.InnerMessage\032J.buf" +
      ".javamultiplefiles.disabled.v1.DisabledO" +
      "uterMessageNested.InnerMessageB\002P\000b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_buf_javamultiplefiles_disabled_v1_DisabledOuterMessageNested_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_buf_javamultiplefiles_disabled_v1_DisabledOuterMessageNested_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_buf_javamultiplefiles_disabled_v1_DisabledOuterMessageNested_descriptor,
        new java.lang.String[] { });
    internal_static_buf_javamultiplefiles_disabled_v1_DisabledOuterMessageNested_InnerMessage_descriptor =
      internal_static_buf_javamultiplefiles_disabled_v1_DisabledOuterMessageNested_descriptor.getNestedTypes().get(0);
    internal_static_buf_javamultiplefiles_disabled_v1_DisabledOuterMessageNested_InnerMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_buf_javamultiplefiles_disabled_v1_DisabledOuterMessageNested_InnerMessage_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
