// Copyright 2022-2023 Buf Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: buf/javamultiplefiles/disabled/v1/disabled.proto

package buf.javamultiplefiles.disabled.v1;

public final class Disabled {
  private Disabled() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DisabledRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:buf.javamultiplefiles.disabled.v1.DisabledRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string sentence = 1 [json_name = "sentence"];</code>
     * @return The sentence.
     */
    java.lang.String getSentence();
    /**
     * <code>string sentence = 1 [json_name = "sentence"];</code>
     * @return The bytes for sentence.
     */
    com.google.protobuf.ByteString
        getSentenceBytes();
  }
  /**
   * Protobuf type {@code buf.javamultiplefiles.disabled.v1.DisabledRequest}
   */
  public static final class DisabledRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:buf.javamultiplefiles.disabled.v1.DisabledRequest)
      DisabledRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DisabledRequest.newBuilder() to construct.
    private DisabledRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DisabledRequest() {
      sentence_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DisabledRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DisabledRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              sentence_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return buf.javamultiplefiles.disabled.v1.Disabled.internal_static_buf_javamultiplefiles_disabled_v1_DisabledRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return buf.javamultiplefiles.disabled.v1.Disabled.internal_static_buf_javamultiplefiles_disabled_v1_DisabledRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              buf.javamultiplefiles.disabled.v1.Disabled.DisabledRequest.class, buf.javamultiplefiles.disabled.v1.Disabled.DisabledRequest.Builder.class);
    }

    public static final int SENTENCE_FIELD_NUMBER = 1;
    private volatile java.lang.Object sentence_;
    /**
     * <code>string sentence = 1 [json_name = "sentence"];</code>
     * @return The sentence.
     */
    @java.lang.Override
    public java.lang.String getSentence() {
      java.lang.Object ref = sentence_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sentence_ = s;
        return s;
      }
    }
    /**
     * <code>string sentence = 1 [json_name = "sentence"];</code>
     * @return The bytes for sentence.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSentenceBytes() {
      java.lang.Object ref = sentence_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sentence_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sentence_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sentence_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sentence_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sentence_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof buf.javamultiplefiles.disabled.v1.Disabled.DisabledRequest)) {
        return super.equals(obj);
      }
      buf.javamultiplefiles.disabled.v1.Disabled.DisabledRequest other = (buf.javamultiplefiles.disabled.v1.Disabled.DisabledRequest) obj;

      if (!getSentence()
          .equals(other.getSentence())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SENTENCE_FIELD_NUMBER;
      hash = (53 * hash) + getSentence().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static buf.javamultiplefiles.disabled.v1.Disabled.DisabledRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static buf.javamultiplefiles.disabled.v1.Disabled.DisabledRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static buf.javamultiplefiles.disabled.v1.Disabled.DisabledRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static buf.javamultiplefiles.disabled.v1.Disabled.DisabledRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static buf.javamultiplefiles.disabled.v1.Disabled.DisabledRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static buf.javamultiplefiles.disabled.v1.Disabled.DisabledRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static buf.javamultiplefiles.disabled.v1.Disabled.DisabledRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static buf.javamultiplefiles.disabled.v1.Disabled.DisabledRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static buf.javamultiplefiles.disabled.v1.Disabled.DisabledRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static buf.javamultiplefiles.disabled.v1.Disabled.DisabledRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static buf.javamultiplefiles.disabled.v1.Disabled.DisabledRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static buf.javamultiplefiles.disabled.v1.Disabled.DisabledRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(buf.javamultiplefiles.disabled.v1.Disabled.DisabledRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code buf.javamultiplefiles.disabled.v1.DisabledRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:buf.javamultiplefiles.disabled.v1.DisabledRequest)
        buf.javamultiplefiles.disabled.v1.Disabled.DisabledRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return buf.javamultiplefiles.disabled.v1.Disabled.internal_static_buf_javamultiplefiles_disabled_v1_DisabledRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return buf.javamultiplefiles.disabled.v1.Disabled.internal_static_buf_javamultiplefiles_disabled_v1_DisabledRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                buf.javamultiplefiles.disabled.v1.Disabled.DisabledRequest.class, buf.javamultiplefiles.disabled.v1.Disabled.DisabledRequest.Builder.class);
      }

      // Construct using buf.javamultiplefiles.disabled.v1.Disabled.DisabledRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        sentence_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return buf.javamultiplefiles.disabled.v1.Disabled.internal_static_buf_javamultiplefiles_disabled_v1_DisabledRequest_descriptor;
      }

      @java.lang.Override
      public buf.javamultiplefiles.disabled.v1.Disabled.DisabledRequest getDefaultInstanceForType() {
        return buf.javamultiplefiles.disabled.v1.Disabled.DisabledRequest.getDefaultInstance();
      }

      @java.lang.Override
      public buf.javamultiplefiles.disabled.v1.Disabled.DisabledRequest build() {
        buf.javamultiplefiles.disabled.v1.Disabled.DisabledRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public buf.javamultiplefiles.disabled.v1.Disabled.DisabledRequest buildPartial() {
        buf.javamultiplefiles.disabled.v1.Disabled.DisabledRequest result = new buf.javamultiplefiles.disabled.v1.Disabled.DisabledRequest(this);
        result.sentence_ = sentence_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof buf.javamultiplefiles.disabled.v1.Disabled.DisabledRequest) {
          return mergeFrom((buf.javamultiplefiles.disabled.v1.Disabled.DisabledRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(buf.javamultiplefiles.disabled.v1.Disabled.DisabledRequest other) {
        if (other == buf.javamultiplefiles.disabled.v1.Disabled.DisabledRequest.getDefaultInstance()) return this;
        if (!other.getSentence().isEmpty()) {
          sentence_ = other.sentence_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        buf.javamultiplefiles.disabled.v1.Disabled.DisabledRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (buf.javamultiplefiles.disabled.v1.Disabled.DisabledRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object sentence_ = "";
      /**
       * <code>string sentence = 1 [json_name = "sentence"];</code>
       * @return The sentence.
       */
      public java.lang.String getSentence() {
        java.lang.Object ref = sentence_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sentence_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sentence = 1 [json_name = "sentence"];</code>
       * @return The bytes for sentence.
       */
      public com.google.protobuf.ByteString
          getSentenceBytes() {
        java.lang.Object ref = sentence_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sentence_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sentence = 1 [json_name = "sentence"];</code>
       * @param value The sentence to set.
       * @return This builder for chaining.
       */
      public Builder setSentence(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sentence_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sentence = 1 [json_name = "sentence"];</code>
       * @return This builder for chaining.
       */
      public Builder clearSentence() {
        
        sentence_ = getDefaultInstance().getSentence();
        onChanged();
        return this;
      }
      /**
       * <code>string sentence = 1 [json_name = "sentence"];</code>
       * @param value The bytes for sentence to set.
       * @return This builder for chaining.
       */
      public Builder setSentenceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sentence_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:buf.javamultiplefiles.disabled.v1.DisabledRequest)
    }

    // @@protoc_insertion_point(class_scope:buf.javamultiplefiles.disabled.v1.DisabledRequest)
    private static final buf.javamultiplefiles.disabled.v1.Disabled.DisabledRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new buf.javamultiplefiles.disabled.v1.Disabled.DisabledRequest();
    }

    public static buf.javamultiplefiles.disabled.v1.Disabled.DisabledRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DisabledRequest>
        PARSER = new com.google.protobuf.AbstractParser<DisabledRequest>() {
      @java.lang.Override
      public DisabledRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DisabledRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DisabledRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DisabledRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public buf.javamultiplefiles.disabled.v1.Disabled.DisabledRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DisabledResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:buf.javamultiplefiles.disabled.v1.DisabledResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string sentence = 1 [json_name = "sentence"];</code>
     * @return The sentence.
     */
    java.lang.String getSentence();
    /**
     * <code>string sentence = 1 [json_name = "sentence"];</code>
     * @return The bytes for sentence.
     */
    com.google.protobuf.ByteString
        getSentenceBytes();
  }
  /**
   * Protobuf type {@code buf.javamultiplefiles.disabled.v1.DisabledResponse}
   */
  public static final class DisabledResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:buf.javamultiplefiles.disabled.v1.DisabledResponse)
      DisabledResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DisabledResponse.newBuilder() to construct.
    private DisabledResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DisabledResponse() {
      sentence_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DisabledResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DisabledResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              sentence_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return buf.javamultiplefiles.disabled.v1.Disabled.internal_static_buf_javamultiplefiles_disabled_v1_DisabledResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return buf.javamultiplefiles.disabled.v1.Disabled.internal_static_buf_javamultiplefiles_disabled_v1_DisabledResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              buf.javamultiplefiles.disabled.v1.Disabled.DisabledResponse.class, buf.javamultiplefiles.disabled.v1.Disabled.DisabledResponse.Builder.class);
    }

    public static final int SENTENCE_FIELD_NUMBER = 1;
    private volatile java.lang.Object sentence_;
    /**
     * <code>string sentence = 1 [json_name = "sentence"];</code>
     * @return The sentence.
     */
    @java.lang.Override
    public java.lang.String getSentence() {
      java.lang.Object ref = sentence_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sentence_ = s;
        return s;
      }
    }
    /**
     * <code>string sentence = 1 [json_name = "sentence"];</code>
     * @return The bytes for sentence.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSentenceBytes() {
      java.lang.Object ref = sentence_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sentence_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sentence_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sentence_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sentence_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sentence_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof buf.javamultiplefiles.disabled.v1.Disabled.DisabledResponse)) {
        return super.equals(obj);
      }
      buf.javamultiplefiles.disabled.v1.Disabled.DisabledResponse other = (buf.javamultiplefiles.disabled.v1.Disabled.DisabledResponse) obj;

      if (!getSentence()
          .equals(other.getSentence())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SENTENCE_FIELD_NUMBER;
      hash = (53 * hash) + getSentence().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static buf.javamultiplefiles.disabled.v1.Disabled.DisabledResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static buf.javamultiplefiles.disabled.v1.Disabled.DisabledResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static buf.javamultiplefiles.disabled.v1.Disabled.DisabledResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static buf.javamultiplefiles.disabled.v1.Disabled.DisabledResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static buf.javamultiplefiles.disabled.v1.Disabled.DisabledResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static buf.javamultiplefiles.disabled.v1.Disabled.DisabledResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static buf.javamultiplefiles.disabled.v1.Disabled.DisabledResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static buf.javamultiplefiles.disabled.v1.Disabled.DisabledResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static buf.javamultiplefiles.disabled.v1.Disabled.DisabledResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static buf.javamultiplefiles.disabled.v1.Disabled.DisabledResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static buf.javamultiplefiles.disabled.v1.Disabled.DisabledResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static buf.javamultiplefiles.disabled.v1.Disabled.DisabledResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(buf.javamultiplefiles.disabled.v1.Disabled.DisabledResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code buf.javamultiplefiles.disabled.v1.DisabledResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:buf.javamultiplefiles.disabled.v1.DisabledResponse)
        buf.javamultiplefiles.disabled.v1.Disabled.DisabledResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return buf.javamultiplefiles.disabled.v1.Disabled.internal_static_buf_javamultiplefiles_disabled_v1_DisabledResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return buf.javamultiplefiles.disabled.v1.Disabled.internal_static_buf_javamultiplefiles_disabled_v1_DisabledResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                buf.javamultiplefiles.disabled.v1.Disabled.DisabledResponse.class, buf.javamultiplefiles.disabled.v1.Disabled.DisabledResponse.Builder.class);
      }

      // Construct using buf.javamultiplefiles.disabled.v1.Disabled.DisabledResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        sentence_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return buf.javamultiplefiles.disabled.v1.Disabled.internal_static_buf_javamultiplefiles_disabled_v1_DisabledResponse_descriptor;
      }

      @java.lang.Override
      public buf.javamultiplefiles.disabled.v1.Disabled.DisabledResponse getDefaultInstanceForType() {
        return buf.javamultiplefiles.disabled.v1.Disabled.DisabledResponse.getDefaultInstance();
      }

      @java.lang.Override
      public buf.javamultiplefiles.disabled.v1.Disabled.DisabledResponse build() {
        buf.javamultiplefiles.disabled.v1.Disabled.DisabledResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public buf.javamultiplefiles.disabled.v1.Disabled.DisabledResponse buildPartial() {
        buf.javamultiplefiles.disabled.v1.Disabled.DisabledResponse result = new buf.javamultiplefiles.disabled.v1.Disabled.DisabledResponse(this);
        result.sentence_ = sentence_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof buf.javamultiplefiles.disabled.v1.Disabled.DisabledResponse) {
          return mergeFrom((buf.javamultiplefiles.disabled.v1.Disabled.DisabledResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(buf.javamultiplefiles.disabled.v1.Disabled.DisabledResponse other) {
        if (other == buf.javamultiplefiles.disabled.v1.Disabled.DisabledResponse.getDefaultInstance()) return this;
        if (!other.getSentence().isEmpty()) {
          sentence_ = other.sentence_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        buf.javamultiplefiles.disabled.v1.Disabled.DisabledResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (buf.javamultiplefiles.disabled.v1.Disabled.DisabledResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object sentence_ = "";
      /**
       * <code>string sentence = 1 [json_name = "sentence"];</code>
       * @return The sentence.
       */
      public java.lang.String getSentence() {
        java.lang.Object ref = sentence_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sentence_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sentence = 1 [json_name = "sentence"];</code>
       * @return The bytes for sentence.
       */
      public com.google.protobuf.ByteString
          getSentenceBytes() {
        java.lang.Object ref = sentence_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sentence_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sentence = 1 [json_name = "sentence"];</code>
       * @param value The sentence to set.
       * @return This builder for chaining.
       */
      public Builder setSentence(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sentence_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sentence = 1 [json_name = "sentence"];</code>
       * @return This builder for chaining.
       */
      public Builder clearSentence() {
        
        sentence_ = getDefaultInstance().getSentence();
        onChanged();
        return this;
      }
      /**
       * <code>string sentence = 1 [json_name = "sentence"];</code>
       * @param value The bytes for sentence to set.
       * @return This builder for chaining.
       */
      public Builder setSentenceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sentence_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:buf.javamultiplefiles.disabled.v1.DisabledResponse)
    }

    // @@protoc_insertion_point(class_scope:buf.javamultiplefiles.disabled.v1.DisabledResponse)
    private static final buf.javamultiplefiles.disabled.v1.Disabled.DisabledResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new buf.javamultiplefiles.disabled.v1.Disabled.DisabledResponse();
    }

    public static buf.javamultiplefiles.disabled.v1.Disabled.DisabledResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DisabledResponse>
        PARSER = new com.google.protobuf.AbstractParser<DisabledResponse>() {
      @java.lang.Override
      public DisabledResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DisabledResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DisabledResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DisabledResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public buf.javamultiplefiles.disabled.v1.Disabled.DisabledResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_buf_javamultiplefiles_disabled_v1_DisabledRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_buf_javamultiplefiles_disabled_v1_DisabledRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_buf_javamultiplefiles_disabled_v1_DisabledResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_buf_javamultiplefiles_disabled_v1_DisabledResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n0buf/javamultiplefiles/disabled/v1/disa" +
      "bled.proto\022!buf.javamultiplefiles.disabl" +
      "ed.v1\"-\n\017DisabledRequest\022\032\n\010sentence\030\001 \001" +
      "(\tR\010sentence\".\n\020DisabledResponse\022\032\n\010sent" +
      "ence\030\001 \001(\tR\010sentence2\210\001\n\017DisabledService" +
      "\022u\n\010Disabled\0222.buf.javamultiplefiles.dis" +
      "abled.v1.DisabledRequest\0323.buf.javamulti" +
      "plefiles.disabled.v1.DisabledResponse\"\000B" +
      "\002P\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_buf_javamultiplefiles_disabled_v1_DisabledRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_buf_javamultiplefiles_disabled_v1_DisabledRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_buf_javamultiplefiles_disabled_v1_DisabledRequest_descriptor,
        new java.lang.String[] { "Sentence", });
    internal_static_buf_javamultiplefiles_disabled_v1_DisabledResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_buf_javamultiplefiles_disabled_v1_DisabledResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_buf_javamultiplefiles_disabled_v1_DisabledResponse_descriptor,
        new java.lang.String[] { "Sentence", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
