// Copyright 2022-2023 Buf Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: buf/javamultiplefiles/enabled/v1/enabled_empty.proto

package buf.javamultiplefiles.enabled.v1;

public final class EnabledEmptyOuterClass {
  private EnabledEmptyOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_buf_javamultiplefiles_enabled_v1_EnabledEmpty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_buf_javamultiplefiles_enabled_v1_EnabledEmpty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_buf_javamultiplefiles_enabled_v1_EnabledEmptyRPCRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_buf_javamultiplefiles_enabled_v1_EnabledEmptyRPCRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_buf_javamultiplefiles_enabled_v1_EnabledEmptyRPCResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_buf_javamultiplefiles_enabled_v1_EnabledEmptyRPCResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n4buf/javamultiplefiles/enabled/v1/enabl" +
      "ed_empty.proto\022 buf.javamultiplefiles.en" +
      "abled.v1\"\016\n\014EnabledEmpty\"\030\n\026EnabledEmpty" +
      "RPCRequest\"\031\n\027EnabledEmptyRPCResponse2\236\001" +
      "\n\023EnabledEmptyService\022\206\001\n\017EnabledEmptyRP" +
      "C\0228.buf.javamultiplefiles.enabled.v1.Ena" +
      "bledEmptyRPCRequest\0329.buf.javamultiplefi" +
      "les.enabled.v1.EnabledEmptyRPCResponseB\002" +
      "P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_buf_javamultiplefiles_enabled_v1_EnabledEmpty_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_buf_javamultiplefiles_enabled_v1_EnabledEmpty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_buf_javamultiplefiles_enabled_v1_EnabledEmpty_descriptor,
        new java.lang.String[] { });
    internal_static_buf_javamultiplefiles_enabled_v1_EnabledEmptyRPCRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_buf_javamultiplefiles_enabled_v1_EnabledEmptyRPCRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_buf_javamultiplefiles_enabled_v1_EnabledEmptyRPCRequest_descriptor,
        new java.lang.String[] { });
    internal_static_buf_javamultiplefiles_enabled_v1_EnabledEmptyRPCResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_buf_javamultiplefiles_enabled_v1_EnabledEmptyRPCResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_buf_javamultiplefiles_enabled_v1_EnabledEmptyRPCResponse_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
