// Copyright 2022-2023 Buf Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: buf/javamultiplefiles/enabled/v1/enabled_nested.proto

package buf.javamultiplefiles.enabled.v1;

public final class EnabledNested {
  private EnabledNested() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_buf_javamultiplefiles_enabled_v1_EnabledOuterMessageNested_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_buf_javamultiplefiles_enabled_v1_EnabledOuterMessageNested_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_buf_javamultiplefiles_enabled_v1_EnabledOuterMessageNested_InnerMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_buf_javamultiplefiles_enabled_v1_EnabledOuterMessageNested_InnerMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n5buf/javamultiplefiles/enabled/v1/enabl" +
      "ed_nested.proto\022 buf.javamultiplefiles.e" +
      "nabled.v1\"+\n\031EnabledOuterMessageNested\032\016" +
      "\n\014InnerMessage2\313\001\n\032EnabledInnerMessageSe" +
      "rvice\022\254\001\n\026EnabledInnerMessageRPC\022H.buf.j" +
      "avamultiplefiles.enabled.v1.EnabledOuter" +
      "MessageNested.InnerMessage\032H.buf.javamul" +
      "tiplefiles.enabled.v1.EnabledOuterMessag" +
      "eNested.InnerMessageB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_buf_javamultiplefiles_enabled_v1_EnabledOuterMessageNested_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_buf_javamultiplefiles_enabled_v1_EnabledOuterMessageNested_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_buf_javamultiplefiles_enabled_v1_EnabledOuterMessageNested_descriptor,
        new java.lang.String[] { });
    internal_static_buf_javamultiplefiles_enabled_v1_EnabledOuterMessageNested_InnerMessage_descriptor =
      internal_static_buf_javamultiplefiles_enabled_v1_EnabledOuterMessageNested_descriptor.getNestedTypes().get(0);
    internal_static_buf_javamultiplefiles_enabled_v1_EnabledOuterMessageNested_InnerMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_buf_javamultiplefiles_enabled_v1_EnabledOuterMessageNested_InnerMessage_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
