// Copyright 2022-2023 Buf Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: buf/javamultiplefiles/enabled/v1/enabled.proto

package buf.javamultiplefiles.enabled.v1;

public final class Enabled {
  private Enabled() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_buf_javamultiplefiles_enabled_v1_EnabledRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_buf_javamultiplefiles_enabled_v1_EnabledRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_buf_javamultiplefiles_enabled_v1_EnabledResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_buf_javamultiplefiles_enabled_v1_EnabledResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n.buf/javamultiplefiles/enabled/v1/enabl" +
      "ed.proto\022 buf.javamultiplefiles.enabled." +
      "v1\",\n\016EnabledRequest\022\032\n\010sentence\030\001 \001(\tR\010" +
      "sentence\"-\n\017EnabledResponse\022\032\n\010sentence\030" +
      "\001 \001(\tR\010sentence2\202\001\n\016EnabledService\022p\n\007En" +
      "abled\0220.buf.javamultiplefiles.enabled.v1" +
      ".EnabledRequest\0321.buf.javamultiplefiles." +
      "enabled.v1.EnabledResponse\"\000B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_buf_javamultiplefiles_enabled_v1_EnabledRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_buf_javamultiplefiles_enabled_v1_EnabledRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_buf_javamultiplefiles_enabled_v1_EnabledRequest_descriptor,
        new java.lang.String[] { "Sentence", });
    internal_static_buf_javamultiplefiles_enabled_v1_EnabledResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_buf_javamultiplefiles_enabled_v1_EnabledResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_buf_javamultiplefiles_enabled_v1_EnabledResponse_descriptor,
        new java.lang.String[] { "Sentence", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
