// Copyright 2022-2023 Buf Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: buf/javamultiplefiles/unspecified/v1/unspecified_empty.proto

package buf.javamultiplefiles.unspecified.v1;

public final class UnspecifiedEmptyOuterClass {
  private UnspecifiedEmptyOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UnspecifiedEmptyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:buf.javamultiplefiles.unspecified.v1.UnspecifiedEmpty)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code buf.javamultiplefiles.unspecified.v1.UnspecifiedEmpty}
   */
  public static final class UnspecifiedEmpty extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:buf.javamultiplefiles.unspecified.v1.UnspecifiedEmpty)
      UnspecifiedEmptyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UnspecifiedEmpty.newBuilder() to construct.
    private UnspecifiedEmpty(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UnspecifiedEmpty() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UnspecifiedEmpty();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UnspecifiedEmpty(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.internal_static_buf_javamultiplefiles_unspecified_v1_UnspecifiedEmpty_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.internal_static_buf_javamultiplefiles_unspecified_v1_UnspecifiedEmpty_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmpty.class, buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmpty.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmpty)) {
        return super.equals(obj);
      }
      buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmpty other = (buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmpty) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmpty parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmpty parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmpty parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmpty parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmpty parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmpty parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmpty parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmpty parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmpty parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmpty parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmpty parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmpty parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmpty prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code buf.javamultiplefiles.unspecified.v1.UnspecifiedEmpty}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:buf.javamultiplefiles.unspecified.v1.UnspecifiedEmpty)
        buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.internal_static_buf_javamultiplefiles_unspecified_v1_UnspecifiedEmpty_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.internal_static_buf_javamultiplefiles_unspecified_v1_UnspecifiedEmpty_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmpty.class, buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmpty.Builder.class);
      }

      // Construct using buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmpty.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.internal_static_buf_javamultiplefiles_unspecified_v1_UnspecifiedEmpty_descriptor;
      }

      @java.lang.Override
      public buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmpty getDefaultInstanceForType() {
        return buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmpty.getDefaultInstance();
      }

      @java.lang.Override
      public buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmpty build() {
        buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmpty result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmpty buildPartial() {
        buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmpty result = new buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmpty(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmpty) {
          return mergeFrom((buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmpty)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmpty other) {
        if (other == buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmpty.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmpty parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmpty) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:buf.javamultiplefiles.unspecified.v1.UnspecifiedEmpty)
    }

    // @@protoc_insertion_point(class_scope:buf.javamultiplefiles.unspecified.v1.UnspecifiedEmpty)
    private static final buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmpty DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmpty();
    }

    public static buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmpty getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UnspecifiedEmpty>
        PARSER = new com.google.protobuf.AbstractParser<UnspecifiedEmpty>() {
      @java.lang.Override
      public UnspecifiedEmpty parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UnspecifiedEmpty(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UnspecifiedEmpty> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UnspecifiedEmpty> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmpty getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UnspecifiedEmptyRPCRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyRPCRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyRPCRequest}
   */
  public static final class UnspecifiedEmptyRPCRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyRPCRequest)
      UnspecifiedEmptyRPCRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UnspecifiedEmptyRPCRequest.newBuilder() to construct.
    private UnspecifiedEmptyRPCRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UnspecifiedEmptyRPCRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UnspecifiedEmptyRPCRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UnspecifiedEmptyRPCRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.internal_static_buf_javamultiplefiles_unspecified_v1_UnspecifiedEmptyRPCRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.internal_static_buf_javamultiplefiles_unspecified_v1_UnspecifiedEmptyRPCRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCRequest.class, buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCRequest.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCRequest)) {
        return super.equals(obj);
      }
      buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCRequest other = (buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCRequest) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyRPCRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyRPCRequest)
        buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.internal_static_buf_javamultiplefiles_unspecified_v1_UnspecifiedEmptyRPCRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.internal_static_buf_javamultiplefiles_unspecified_v1_UnspecifiedEmptyRPCRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCRequest.class, buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCRequest.Builder.class);
      }

      // Construct using buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.internal_static_buf_javamultiplefiles_unspecified_v1_UnspecifiedEmptyRPCRequest_descriptor;
      }

      @java.lang.Override
      public buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCRequest getDefaultInstanceForType() {
        return buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCRequest.getDefaultInstance();
      }

      @java.lang.Override
      public buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCRequest build() {
        buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCRequest buildPartial() {
        buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCRequest result = new buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCRequest(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCRequest) {
          return mergeFrom((buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCRequest other) {
        if (other == buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyRPCRequest)
    }

    // @@protoc_insertion_point(class_scope:buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyRPCRequest)
    private static final buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCRequest();
    }

    public static buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UnspecifiedEmptyRPCRequest>
        PARSER = new com.google.protobuf.AbstractParser<UnspecifiedEmptyRPCRequest>() {
      @java.lang.Override
      public UnspecifiedEmptyRPCRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UnspecifiedEmptyRPCRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UnspecifiedEmptyRPCRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UnspecifiedEmptyRPCRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UnspecifiedEmptyRPCResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyRPCResponse)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyRPCResponse}
   */
  public static final class UnspecifiedEmptyRPCResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyRPCResponse)
      UnspecifiedEmptyRPCResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UnspecifiedEmptyRPCResponse.newBuilder() to construct.
    private UnspecifiedEmptyRPCResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UnspecifiedEmptyRPCResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UnspecifiedEmptyRPCResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UnspecifiedEmptyRPCResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.internal_static_buf_javamultiplefiles_unspecified_v1_UnspecifiedEmptyRPCResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.internal_static_buf_javamultiplefiles_unspecified_v1_UnspecifiedEmptyRPCResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCResponse.class, buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCResponse.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCResponse)) {
        return super.equals(obj);
      }
      buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCResponse other = (buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCResponse) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyRPCResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyRPCResponse)
        buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.internal_static_buf_javamultiplefiles_unspecified_v1_UnspecifiedEmptyRPCResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.internal_static_buf_javamultiplefiles_unspecified_v1_UnspecifiedEmptyRPCResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCResponse.class, buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCResponse.Builder.class);
      }

      // Construct using buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.internal_static_buf_javamultiplefiles_unspecified_v1_UnspecifiedEmptyRPCResponse_descriptor;
      }

      @java.lang.Override
      public buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCResponse getDefaultInstanceForType() {
        return buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCResponse.getDefaultInstance();
      }

      @java.lang.Override
      public buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCResponse build() {
        buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCResponse buildPartial() {
        buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCResponse result = new buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCResponse(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCResponse) {
          return mergeFrom((buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCResponse other) {
        if (other == buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCResponse.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyRPCResponse)
    }

    // @@protoc_insertion_point(class_scope:buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyRPCResponse)
    private static final buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCResponse();
    }

    public static buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UnspecifiedEmptyRPCResponse>
        PARSER = new com.google.protobuf.AbstractParser<UnspecifiedEmptyRPCResponse>() {
      @java.lang.Override
      public UnspecifiedEmptyRPCResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UnspecifiedEmptyRPCResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UnspecifiedEmptyRPCResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UnspecifiedEmptyRPCResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public buf.javamultiplefiles.unspecified.v1.UnspecifiedEmptyOuterClass.UnspecifiedEmptyRPCResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_buf_javamultiplefiles_unspecified_v1_UnspecifiedEmpty_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_buf_javamultiplefiles_unspecified_v1_UnspecifiedEmpty_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_buf_javamultiplefiles_unspecified_v1_UnspecifiedEmptyRPCRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_buf_javamultiplefiles_unspecified_v1_UnspecifiedEmptyRPCRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_buf_javamultiplefiles_unspecified_v1_UnspecifiedEmptyRPCResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_buf_javamultiplefiles_unspecified_v1_UnspecifiedEmptyRPCResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n<buf/javamultiplefiles/unspecified/v1/u" +
      "nspecified_empty.proto\022$buf.javamultiple" +
      "files.unspecified.v1\"\022\n\020UnspecifiedEmpty" +
      "\"\034\n\032UnspecifiedEmptyRPCRequest\"\035\n\033Unspec" +
      "ifiedEmptyRPCResponse2\266\001\n\027UnspecifiedEmp" +
      "tyService\022\232\001\n\023UnspecifiedEmptyRPC\022@.buf." +
      "javamultiplefiles.unspecified.v1.Unspeci" +
      "fiedEmptyRPCRequest\032A.buf.javamultiplefi" +
      "les.unspecified.v1.UnspecifiedEmptyRPCRe" +
      "sponseb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_buf_javamultiplefiles_unspecified_v1_UnspecifiedEmpty_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_buf_javamultiplefiles_unspecified_v1_UnspecifiedEmpty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_buf_javamultiplefiles_unspecified_v1_UnspecifiedEmpty_descriptor,
        new java.lang.String[] { });
    internal_static_buf_javamultiplefiles_unspecified_v1_UnspecifiedEmptyRPCRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_buf_javamultiplefiles_unspecified_v1_UnspecifiedEmptyRPCRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_buf_javamultiplefiles_unspecified_v1_UnspecifiedEmptyRPCRequest_descriptor,
        new java.lang.String[] { });
    internal_static_buf_javamultiplefiles_unspecified_v1_UnspecifiedEmptyRPCResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_buf_javamultiplefiles_unspecified_v1_UnspecifiedEmptyRPCResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_buf_javamultiplefiles_unspecified_v1_UnspecifiedEmptyRPCResponse_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
