// Copyright 2022-2023 Buf Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server/v1/server.proto

package server.v1;

public final class Server {
  private Server() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code server.v1.Protocol}
   */
  public enum Protocol
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>PROTOCOL_UNSPECIFIED = 0;</code>
     */
    PROTOCOL_UNSPECIFIED(0),
    /**
     * <code>PROTOCOL_GRPC = 1;</code>
     */
    PROTOCOL_GRPC(1),
    /**
     * <code>PROTOCOL_GRPC_WEB = 2;</code>
     */
    PROTOCOL_GRPC_WEB(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>PROTOCOL_UNSPECIFIED = 0;</code>
     */
    public static final int PROTOCOL_UNSPECIFIED_VALUE = 0;
    /**
     * <code>PROTOCOL_GRPC = 1;</code>
     */
    public static final int PROTOCOL_GRPC_VALUE = 1;
    /**
     * <code>PROTOCOL_GRPC_WEB = 2;</code>
     */
    public static final int PROTOCOL_GRPC_WEB_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Protocol valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Protocol forNumber(int value) {
      switch (value) {
        case 0: return PROTOCOL_UNSPECIFIED;
        case 1: return PROTOCOL_GRPC;
        case 2: return PROTOCOL_GRPC_WEB;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Protocol>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Protocol> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Protocol>() {
            public Protocol findValueByNumber(int number) {
              return Protocol.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return server.v1.Server.getDescriptor().getEnumTypes().get(0);
    }

    private static final Protocol[] VALUES = values();

    public static Protocol valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Protocol(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:server.v1.Protocol)
  }

  public interface ServerMetadataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:server.v1.ServerMetadata)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string host = 1 [json_name = "host"];</code>
     * @return The host.
     */
    java.lang.String getHost();
    /**
     * <code>string host = 1 [json_name = "host"];</code>
     * @return The bytes for host.
     */
    com.google.protobuf.ByteString
        getHostBytes();

    /**
     * <code>repeated .server.v1.ProtocolSupport protocols = 2 [json_name = "protocols"];</code>
     */
    java.util.List<server.v1.Server.ProtocolSupport> 
        getProtocolsList();
    /**
     * <code>repeated .server.v1.ProtocolSupport protocols = 2 [json_name = "protocols"];</code>
     */
    server.v1.Server.ProtocolSupport getProtocols(int index);
    /**
     * <code>repeated .server.v1.ProtocolSupport protocols = 2 [json_name = "protocols"];</code>
     */
    int getProtocolsCount();
    /**
     * <code>repeated .server.v1.ProtocolSupport protocols = 2 [json_name = "protocols"];</code>
     */
    java.util.List<? extends server.v1.Server.ProtocolSupportOrBuilder> 
        getProtocolsOrBuilderList();
    /**
     * <code>repeated .server.v1.ProtocolSupport protocols = 2 [json_name = "protocols"];</code>
     */
    server.v1.Server.ProtocolSupportOrBuilder getProtocolsOrBuilder(
        int index);
  }
  /**
   * <pre>
   * ServerMetadata is the metadata returned from the server started by the server binary.
   * </pre>
   *
   * Protobuf type {@code server.v1.ServerMetadata}
   */
  public static final class ServerMetadata extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:server.v1.ServerMetadata)
      ServerMetadataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ServerMetadata.newBuilder() to construct.
    private ServerMetadata(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ServerMetadata() {
      host_ = "";
      protocols_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ServerMetadata();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ServerMetadata(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              host_ = s;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                protocols_ = new java.util.ArrayList<server.v1.Server.ProtocolSupport>();
                mutable_bitField0_ |= 0x00000001;
              }
              protocols_.add(
                  input.readMessage(server.v1.Server.ProtocolSupport.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          protocols_ = java.util.Collections.unmodifiableList(protocols_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return server.v1.Server.internal_static_server_v1_ServerMetadata_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return server.v1.Server.internal_static_server_v1_ServerMetadata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              server.v1.Server.ServerMetadata.class, server.v1.Server.ServerMetadata.Builder.class);
    }

    public static final int HOST_FIELD_NUMBER = 1;
    private volatile java.lang.Object host_;
    /**
     * <code>string host = 1 [json_name = "host"];</code>
     * @return The host.
     */
    @java.lang.Override
    public java.lang.String getHost() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        host_ = s;
        return s;
      }
    }
    /**
     * <code>string host = 1 [json_name = "host"];</code>
     * @return The bytes for host.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHostBytes() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        host_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROTOCOLS_FIELD_NUMBER = 2;
    private java.util.List<server.v1.Server.ProtocolSupport> protocols_;
    /**
     * <code>repeated .server.v1.ProtocolSupport protocols = 2 [json_name = "protocols"];</code>
     */
    @java.lang.Override
    public java.util.List<server.v1.Server.ProtocolSupport> getProtocolsList() {
      return protocols_;
    }
    /**
     * <code>repeated .server.v1.ProtocolSupport protocols = 2 [json_name = "protocols"];</code>
     */
    @java.lang.Override
    public java.util.List<? extends server.v1.Server.ProtocolSupportOrBuilder> 
        getProtocolsOrBuilderList() {
      return protocols_;
    }
    /**
     * <code>repeated .server.v1.ProtocolSupport protocols = 2 [json_name = "protocols"];</code>
     */
    @java.lang.Override
    public int getProtocolsCount() {
      return protocols_.size();
    }
    /**
     * <code>repeated .server.v1.ProtocolSupport protocols = 2 [json_name = "protocols"];</code>
     */
    @java.lang.Override
    public server.v1.Server.ProtocolSupport getProtocols(int index) {
      return protocols_.get(index);
    }
    /**
     * <code>repeated .server.v1.ProtocolSupport protocols = 2 [json_name = "protocols"];</code>
     */
    @java.lang.Override
    public server.v1.Server.ProtocolSupportOrBuilder getProtocolsOrBuilder(
        int index) {
      return protocols_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(host_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, host_);
      }
      for (int i = 0; i < protocols_.size(); i++) {
        output.writeMessage(2, protocols_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(host_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, host_);
      }
      for (int i = 0; i < protocols_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, protocols_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof server.v1.Server.ServerMetadata)) {
        return super.equals(obj);
      }
      server.v1.Server.ServerMetadata other = (server.v1.Server.ServerMetadata) obj;

      if (!getHost()
          .equals(other.getHost())) return false;
      if (!getProtocolsList()
          .equals(other.getProtocolsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + HOST_FIELD_NUMBER;
      hash = (53 * hash) + getHost().hashCode();
      if (getProtocolsCount() > 0) {
        hash = (37 * hash) + PROTOCOLS_FIELD_NUMBER;
        hash = (53 * hash) + getProtocolsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static server.v1.Server.ServerMetadata parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static server.v1.Server.ServerMetadata parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static server.v1.Server.ServerMetadata parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static server.v1.Server.ServerMetadata parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static server.v1.Server.ServerMetadata parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static server.v1.Server.ServerMetadata parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static server.v1.Server.ServerMetadata parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static server.v1.Server.ServerMetadata parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static server.v1.Server.ServerMetadata parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static server.v1.Server.ServerMetadata parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static server.v1.Server.ServerMetadata parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static server.v1.Server.ServerMetadata parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(server.v1.Server.ServerMetadata prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * ServerMetadata is the metadata returned from the server started by the server binary.
     * </pre>
     *
     * Protobuf type {@code server.v1.ServerMetadata}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:server.v1.ServerMetadata)
        server.v1.Server.ServerMetadataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return server.v1.Server.internal_static_server_v1_ServerMetadata_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return server.v1.Server.internal_static_server_v1_ServerMetadata_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                server.v1.Server.ServerMetadata.class, server.v1.Server.ServerMetadata.Builder.class);
      }

      // Construct using server.v1.Server.ServerMetadata.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getProtocolsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        host_ = "";

        if (protocolsBuilder_ == null) {
          protocols_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          protocolsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return server.v1.Server.internal_static_server_v1_ServerMetadata_descriptor;
      }

      @java.lang.Override
      public server.v1.Server.ServerMetadata getDefaultInstanceForType() {
        return server.v1.Server.ServerMetadata.getDefaultInstance();
      }

      @java.lang.Override
      public server.v1.Server.ServerMetadata build() {
        server.v1.Server.ServerMetadata result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public server.v1.Server.ServerMetadata buildPartial() {
        server.v1.Server.ServerMetadata result = new server.v1.Server.ServerMetadata(this);
        int from_bitField0_ = bitField0_;
        result.host_ = host_;
        if (protocolsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            protocols_ = java.util.Collections.unmodifiableList(protocols_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.protocols_ = protocols_;
        } else {
          result.protocols_ = protocolsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof server.v1.Server.ServerMetadata) {
          return mergeFrom((server.v1.Server.ServerMetadata)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(server.v1.Server.ServerMetadata other) {
        if (other == server.v1.Server.ServerMetadata.getDefaultInstance()) return this;
        if (!other.getHost().isEmpty()) {
          host_ = other.host_;
          onChanged();
        }
        if (protocolsBuilder_ == null) {
          if (!other.protocols_.isEmpty()) {
            if (protocols_.isEmpty()) {
              protocols_ = other.protocols_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureProtocolsIsMutable();
              protocols_.addAll(other.protocols_);
            }
            onChanged();
          }
        } else {
          if (!other.protocols_.isEmpty()) {
            if (protocolsBuilder_.isEmpty()) {
              protocolsBuilder_.dispose();
              protocolsBuilder_ = null;
              protocols_ = other.protocols_;
              bitField0_ = (bitField0_ & ~0x00000001);
              protocolsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getProtocolsFieldBuilder() : null;
            } else {
              protocolsBuilder_.addAllMessages(other.protocols_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        server.v1.Server.ServerMetadata parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (server.v1.Server.ServerMetadata) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object host_ = "";
      /**
       * <code>string host = 1 [json_name = "host"];</code>
       * @return The host.
       */
      public java.lang.String getHost() {
        java.lang.Object ref = host_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          host_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string host = 1 [json_name = "host"];</code>
       * @return The bytes for host.
       */
      public com.google.protobuf.ByteString
          getHostBytes() {
        java.lang.Object ref = host_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          host_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string host = 1 [json_name = "host"];</code>
       * @param value The host to set.
       * @return This builder for chaining.
       */
      public Builder setHost(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        host_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string host = 1 [json_name = "host"];</code>
       * @return This builder for chaining.
       */
      public Builder clearHost() {
        
        host_ = getDefaultInstance().getHost();
        onChanged();
        return this;
      }
      /**
       * <code>string host = 1 [json_name = "host"];</code>
       * @param value The bytes for host to set.
       * @return This builder for chaining.
       */
      public Builder setHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        host_ = value;
        onChanged();
        return this;
      }

      private java.util.List<server.v1.Server.ProtocolSupport> protocols_ =
        java.util.Collections.emptyList();
      private void ensureProtocolsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          protocols_ = new java.util.ArrayList<server.v1.Server.ProtocolSupport>(protocols_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          server.v1.Server.ProtocolSupport, server.v1.Server.ProtocolSupport.Builder, server.v1.Server.ProtocolSupportOrBuilder> protocolsBuilder_;

      /**
       * <code>repeated .server.v1.ProtocolSupport protocols = 2 [json_name = "protocols"];</code>
       */
      public java.util.List<server.v1.Server.ProtocolSupport> getProtocolsList() {
        if (protocolsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(protocols_);
        } else {
          return protocolsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .server.v1.ProtocolSupport protocols = 2 [json_name = "protocols"];</code>
       */
      public int getProtocolsCount() {
        if (protocolsBuilder_ == null) {
          return protocols_.size();
        } else {
          return protocolsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .server.v1.ProtocolSupport protocols = 2 [json_name = "protocols"];</code>
       */
      public server.v1.Server.ProtocolSupport getProtocols(int index) {
        if (protocolsBuilder_ == null) {
          return protocols_.get(index);
        } else {
          return protocolsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .server.v1.ProtocolSupport protocols = 2 [json_name = "protocols"];</code>
       */
      public Builder setProtocols(
          int index, server.v1.Server.ProtocolSupport value) {
        if (protocolsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProtocolsIsMutable();
          protocols_.set(index, value);
          onChanged();
        } else {
          protocolsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .server.v1.ProtocolSupport protocols = 2 [json_name = "protocols"];</code>
       */
      public Builder setProtocols(
          int index, server.v1.Server.ProtocolSupport.Builder builderForValue) {
        if (protocolsBuilder_ == null) {
          ensureProtocolsIsMutable();
          protocols_.set(index, builderForValue.build());
          onChanged();
        } else {
          protocolsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .server.v1.ProtocolSupport protocols = 2 [json_name = "protocols"];</code>
       */
      public Builder addProtocols(server.v1.Server.ProtocolSupport value) {
        if (protocolsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProtocolsIsMutable();
          protocols_.add(value);
          onChanged();
        } else {
          protocolsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .server.v1.ProtocolSupport protocols = 2 [json_name = "protocols"];</code>
       */
      public Builder addProtocols(
          int index, server.v1.Server.ProtocolSupport value) {
        if (protocolsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProtocolsIsMutable();
          protocols_.add(index, value);
          onChanged();
        } else {
          protocolsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .server.v1.ProtocolSupport protocols = 2 [json_name = "protocols"];</code>
       */
      public Builder addProtocols(
          server.v1.Server.ProtocolSupport.Builder builderForValue) {
        if (protocolsBuilder_ == null) {
          ensureProtocolsIsMutable();
          protocols_.add(builderForValue.build());
          onChanged();
        } else {
          protocolsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .server.v1.ProtocolSupport protocols = 2 [json_name = "protocols"];</code>
       */
      public Builder addProtocols(
          int index, server.v1.Server.ProtocolSupport.Builder builderForValue) {
        if (protocolsBuilder_ == null) {
          ensureProtocolsIsMutable();
          protocols_.add(index, builderForValue.build());
          onChanged();
        } else {
          protocolsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .server.v1.ProtocolSupport protocols = 2 [json_name = "protocols"];</code>
       */
      public Builder addAllProtocols(
          java.lang.Iterable<? extends server.v1.Server.ProtocolSupport> values) {
        if (protocolsBuilder_ == null) {
          ensureProtocolsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, protocols_);
          onChanged();
        } else {
          protocolsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .server.v1.ProtocolSupport protocols = 2 [json_name = "protocols"];</code>
       */
      public Builder clearProtocols() {
        if (protocolsBuilder_ == null) {
          protocols_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          protocolsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .server.v1.ProtocolSupport protocols = 2 [json_name = "protocols"];</code>
       */
      public Builder removeProtocols(int index) {
        if (protocolsBuilder_ == null) {
          ensureProtocolsIsMutable();
          protocols_.remove(index);
          onChanged();
        } else {
          protocolsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .server.v1.ProtocolSupport protocols = 2 [json_name = "protocols"];</code>
       */
      public server.v1.Server.ProtocolSupport.Builder getProtocolsBuilder(
          int index) {
        return getProtocolsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .server.v1.ProtocolSupport protocols = 2 [json_name = "protocols"];</code>
       */
      public server.v1.Server.ProtocolSupportOrBuilder getProtocolsOrBuilder(
          int index) {
        if (protocolsBuilder_ == null) {
          return protocols_.get(index);  } else {
          return protocolsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .server.v1.ProtocolSupport protocols = 2 [json_name = "protocols"];</code>
       */
      public java.util.List<? extends server.v1.Server.ProtocolSupportOrBuilder> 
           getProtocolsOrBuilderList() {
        if (protocolsBuilder_ != null) {
          return protocolsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(protocols_);
        }
      }
      /**
       * <code>repeated .server.v1.ProtocolSupport protocols = 2 [json_name = "protocols"];</code>
       */
      public server.v1.Server.ProtocolSupport.Builder addProtocolsBuilder() {
        return getProtocolsFieldBuilder().addBuilder(
            server.v1.Server.ProtocolSupport.getDefaultInstance());
      }
      /**
       * <code>repeated .server.v1.ProtocolSupport protocols = 2 [json_name = "protocols"];</code>
       */
      public server.v1.Server.ProtocolSupport.Builder addProtocolsBuilder(
          int index) {
        return getProtocolsFieldBuilder().addBuilder(
            index, server.v1.Server.ProtocolSupport.getDefaultInstance());
      }
      /**
       * <code>repeated .server.v1.ProtocolSupport protocols = 2 [json_name = "protocols"];</code>
       */
      public java.util.List<server.v1.Server.ProtocolSupport.Builder> 
           getProtocolsBuilderList() {
        return getProtocolsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          server.v1.Server.ProtocolSupport, server.v1.Server.ProtocolSupport.Builder, server.v1.Server.ProtocolSupportOrBuilder> 
          getProtocolsFieldBuilder() {
        if (protocolsBuilder_ == null) {
          protocolsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              server.v1.Server.ProtocolSupport, server.v1.Server.ProtocolSupport.Builder, server.v1.Server.ProtocolSupportOrBuilder>(
                  protocols_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          protocols_ = null;
        }
        return protocolsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:server.v1.ServerMetadata)
    }

    // @@protoc_insertion_point(class_scope:server.v1.ServerMetadata)
    private static final server.v1.Server.ServerMetadata DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new server.v1.Server.ServerMetadata();
    }

    public static server.v1.Server.ServerMetadata getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ServerMetadata>
        PARSER = new com.google.protobuf.AbstractParser<ServerMetadata>() {
      @java.lang.Override
      public ServerMetadata parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ServerMetadata(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ServerMetadata> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ServerMetadata> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public server.v1.Server.ServerMetadata getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ProtocolSupportOrBuilder extends
      // @@protoc_insertion_point(interface_extends:server.v1.ProtocolSupport)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.server.v1.Protocol protocol = 1 [json_name = "protocol"];</code>
     * @return The enum numeric value on the wire for protocol.
     */
    int getProtocolValue();
    /**
     * <code>.server.v1.Protocol protocol = 1 [json_name = "protocol"];</code>
     * @return The protocol.
     */
    server.v1.Server.Protocol getProtocol();

    /**
     * <code>repeated .server.v1.HTTPVersion http_versions = 2 [json_name = "httpVersions"];</code>
     */
    java.util.List<server.v1.Server.HTTPVersion> 
        getHttpVersionsList();
    /**
     * <code>repeated .server.v1.HTTPVersion http_versions = 2 [json_name = "httpVersions"];</code>
     */
    server.v1.Server.HTTPVersion getHttpVersions(int index);
    /**
     * <code>repeated .server.v1.HTTPVersion http_versions = 2 [json_name = "httpVersions"];</code>
     */
    int getHttpVersionsCount();
    /**
     * <code>repeated .server.v1.HTTPVersion http_versions = 2 [json_name = "httpVersions"];</code>
     */
    java.util.List<? extends server.v1.Server.HTTPVersionOrBuilder> 
        getHttpVersionsOrBuilderList();
    /**
     * <code>repeated .server.v1.HTTPVersion http_versions = 2 [json_name = "httpVersions"];</code>
     */
    server.v1.Server.HTTPVersionOrBuilder getHttpVersionsOrBuilder(
        int index);

    /**
     * <code>string port = 3 [json_name = "port"];</code>
     * @return The port.
     */
    java.lang.String getPort();
    /**
     * <code>string port = 3 [json_name = "port"];</code>
     * @return The bytes for port.
     */
    com.google.protobuf.ByteString
        getPortBytes();
  }
  /**
   * Protobuf type {@code server.v1.ProtocolSupport}
   */
  public static final class ProtocolSupport extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:server.v1.ProtocolSupport)
      ProtocolSupportOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProtocolSupport.newBuilder() to construct.
    private ProtocolSupport(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProtocolSupport() {
      protocol_ = 0;
      httpVersions_ = java.util.Collections.emptyList();
      port_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ProtocolSupport();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProtocolSupport(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              protocol_ = rawValue;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                httpVersions_ = new java.util.ArrayList<server.v1.Server.HTTPVersion>();
                mutable_bitField0_ |= 0x00000001;
              }
              httpVersions_.add(
                  input.readMessage(server.v1.Server.HTTPVersion.parser(), extensionRegistry));
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              port_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          httpVersions_ = java.util.Collections.unmodifiableList(httpVersions_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return server.v1.Server.internal_static_server_v1_ProtocolSupport_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return server.v1.Server.internal_static_server_v1_ProtocolSupport_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              server.v1.Server.ProtocolSupport.class, server.v1.Server.ProtocolSupport.Builder.class);
    }

    public static final int PROTOCOL_FIELD_NUMBER = 1;
    private int protocol_;
    /**
     * <code>.server.v1.Protocol protocol = 1 [json_name = "protocol"];</code>
     * @return The enum numeric value on the wire for protocol.
     */
    @java.lang.Override public int getProtocolValue() {
      return protocol_;
    }
    /**
     * <code>.server.v1.Protocol protocol = 1 [json_name = "protocol"];</code>
     * @return The protocol.
     */
    @java.lang.Override public server.v1.Server.Protocol getProtocol() {
      @SuppressWarnings("deprecation")
      server.v1.Server.Protocol result = server.v1.Server.Protocol.valueOf(protocol_);
      return result == null ? server.v1.Server.Protocol.UNRECOGNIZED : result;
    }

    public static final int HTTP_VERSIONS_FIELD_NUMBER = 2;
    private java.util.List<server.v1.Server.HTTPVersion> httpVersions_;
    /**
     * <code>repeated .server.v1.HTTPVersion http_versions = 2 [json_name = "httpVersions"];</code>
     */
    @java.lang.Override
    public java.util.List<server.v1.Server.HTTPVersion> getHttpVersionsList() {
      return httpVersions_;
    }
    /**
     * <code>repeated .server.v1.HTTPVersion http_versions = 2 [json_name = "httpVersions"];</code>
     */
    @java.lang.Override
    public java.util.List<? extends server.v1.Server.HTTPVersionOrBuilder> 
        getHttpVersionsOrBuilderList() {
      return httpVersions_;
    }
    /**
     * <code>repeated .server.v1.HTTPVersion http_versions = 2 [json_name = "httpVersions"];</code>
     */
    @java.lang.Override
    public int getHttpVersionsCount() {
      return httpVersions_.size();
    }
    /**
     * <code>repeated .server.v1.HTTPVersion http_versions = 2 [json_name = "httpVersions"];</code>
     */
    @java.lang.Override
    public server.v1.Server.HTTPVersion getHttpVersions(int index) {
      return httpVersions_.get(index);
    }
    /**
     * <code>repeated .server.v1.HTTPVersion http_versions = 2 [json_name = "httpVersions"];</code>
     */
    @java.lang.Override
    public server.v1.Server.HTTPVersionOrBuilder getHttpVersionsOrBuilder(
        int index) {
      return httpVersions_.get(index);
    }

    public static final int PORT_FIELD_NUMBER = 3;
    private volatile java.lang.Object port_;
    /**
     * <code>string port = 3 [json_name = "port"];</code>
     * @return The port.
     */
    @java.lang.Override
    public java.lang.String getPort() {
      java.lang.Object ref = port_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        port_ = s;
        return s;
      }
    }
    /**
     * <code>string port = 3 [json_name = "port"];</code>
     * @return The bytes for port.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPortBytes() {
      java.lang.Object ref = port_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        port_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (protocol_ != server.v1.Server.Protocol.PROTOCOL_UNSPECIFIED.getNumber()) {
        output.writeEnum(1, protocol_);
      }
      for (int i = 0; i < httpVersions_.size(); i++) {
        output.writeMessage(2, httpVersions_.get(i));
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(port_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, port_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (protocol_ != server.v1.Server.Protocol.PROTOCOL_UNSPECIFIED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, protocol_);
      }
      for (int i = 0; i < httpVersions_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, httpVersions_.get(i));
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(port_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, port_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof server.v1.Server.ProtocolSupport)) {
        return super.equals(obj);
      }
      server.v1.Server.ProtocolSupport other = (server.v1.Server.ProtocolSupport) obj;

      if (protocol_ != other.protocol_) return false;
      if (!getHttpVersionsList()
          .equals(other.getHttpVersionsList())) return false;
      if (!getPort()
          .equals(other.getPort())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PROTOCOL_FIELD_NUMBER;
      hash = (53 * hash) + protocol_;
      if (getHttpVersionsCount() > 0) {
        hash = (37 * hash) + HTTP_VERSIONS_FIELD_NUMBER;
        hash = (53 * hash) + getHttpVersionsList().hashCode();
      }
      hash = (37 * hash) + PORT_FIELD_NUMBER;
      hash = (53 * hash) + getPort().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static server.v1.Server.ProtocolSupport parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static server.v1.Server.ProtocolSupport parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static server.v1.Server.ProtocolSupport parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static server.v1.Server.ProtocolSupport parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static server.v1.Server.ProtocolSupport parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static server.v1.Server.ProtocolSupport parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static server.v1.Server.ProtocolSupport parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static server.v1.Server.ProtocolSupport parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static server.v1.Server.ProtocolSupport parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static server.v1.Server.ProtocolSupport parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static server.v1.Server.ProtocolSupport parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static server.v1.Server.ProtocolSupport parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(server.v1.Server.ProtocolSupport prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code server.v1.ProtocolSupport}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:server.v1.ProtocolSupport)
        server.v1.Server.ProtocolSupportOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return server.v1.Server.internal_static_server_v1_ProtocolSupport_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return server.v1.Server.internal_static_server_v1_ProtocolSupport_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                server.v1.Server.ProtocolSupport.class, server.v1.Server.ProtocolSupport.Builder.class);
      }

      // Construct using server.v1.Server.ProtocolSupport.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getHttpVersionsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        protocol_ = 0;

        if (httpVersionsBuilder_ == null) {
          httpVersions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          httpVersionsBuilder_.clear();
        }
        port_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return server.v1.Server.internal_static_server_v1_ProtocolSupport_descriptor;
      }

      @java.lang.Override
      public server.v1.Server.ProtocolSupport getDefaultInstanceForType() {
        return server.v1.Server.ProtocolSupport.getDefaultInstance();
      }

      @java.lang.Override
      public server.v1.Server.ProtocolSupport build() {
        server.v1.Server.ProtocolSupport result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public server.v1.Server.ProtocolSupport buildPartial() {
        server.v1.Server.ProtocolSupport result = new server.v1.Server.ProtocolSupport(this);
        int from_bitField0_ = bitField0_;
        result.protocol_ = protocol_;
        if (httpVersionsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            httpVersions_ = java.util.Collections.unmodifiableList(httpVersions_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.httpVersions_ = httpVersions_;
        } else {
          result.httpVersions_ = httpVersionsBuilder_.build();
        }
        result.port_ = port_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof server.v1.Server.ProtocolSupport) {
          return mergeFrom((server.v1.Server.ProtocolSupport)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(server.v1.Server.ProtocolSupport other) {
        if (other == server.v1.Server.ProtocolSupport.getDefaultInstance()) return this;
        if (other.protocol_ != 0) {
          setProtocolValue(other.getProtocolValue());
        }
        if (httpVersionsBuilder_ == null) {
          if (!other.httpVersions_.isEmpty()) {
            if (httpVersions_.isEmpty()) {
              httpVersions_ = other.httpVersions_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureHttpVersionsIsMutable();
              httpVersions_.addAll(other.httpVersions_);
            }
            onChanged();
          }
        } else {
          if (!other.httpVersions_.isEmpty()) {
            if (httpVersionsBuilder_.isEmpty()) {
              httpVersionsBuilder_.dispose();
              httpVersionsBuilder_ = null;
              httpVersions_ = other.httpVersions_;
              bitField0_ = (bitField0_ & ~0x00000001);
              httpVersionsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getHttpVersionsFieldBuilder() : null;
            } else {
              httpVersionsBuilder_.addAllMessages(other.httpVersions_);
            }
          }
        }
        if (!other.getPort().isEmpty()) {
          port_ = other.port_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        server.v1.Server.ProtocolSupport parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (server.v1.Server.ProtocolSupport) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int protocol_ = 0;
      /**
       * <code>.server.v1.Protocol protocol = 1 [json_name = "protocol"];</code>
       * @return The enum numeric value on the wire for protocol.
       */
      @java.lang.Override public int getProtocolValue() {
        return protocol_;
      }
      /**
       * <code>.server.v1.Protocol protocol = 1 [json_name = "protocol"];</code>
       * @param value The enum numeric value on the wire for protocol to set.
       * @return This builder for chaining.
       */
      public Builder setProtocolValue(int value) {
        
        protocol_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.server.v1.Protocol protocol = 1 [json_name = "protocol"];</code>
       * @return The protocol.
       */
      @java.lang.Override
      public server.v1.Server.Protocol getProtocol() {
        @SuppressWarnings("deprecation")
        server.v1.Server.Protocol result = server.v1.Server.Protocol.valueOf(protocol_);
        return result == null ? server.v1.Server.Protocol.UNRECOGNIZED : result;
      }
      /**
       * <code>.server.v1.Protocol protocol = 1 [json_name = "protocol"];</code>
       * @param value The protocol to set.
       * @return This builder for chaining.
       */
      public Builder setProtocol(server.v1.Server.Protocol value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        protocol_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.server.v1.Protocol protocol = 1 [json_name = "protocol"];</code>
       * @return This builder for chaining.
       */
      public Builder clearProtocol() {
        
        protocol_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<server.v1.Server.HTTPVersion> httpVersions_ =
        java.util.Collections.emptyList();
      private void ensureHttpVersionsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          httpVersions_ = new java.util.ArrayList<server.v1.Server.HTTPVersion>(httpVersions_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          server.v1.Server.HTTPVersion, server.v1.Server.HTTPVersion.Builder, server.v1.Server.HTTPVersionOrBuilder> httpVersionsBuilder_;

      /**
       * <code>repeated .server.v1.HTTPVersion http_versions = 2 [json_name = "httpVersions"];</code>
       */
      public java.util.List<server.v1.Server.HTTPVersion> getHttpVersionsList() {
        if (httpVersionsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(httpVersions_);
        } else {
          return httpVersionsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .server.v1.HTTPVersion http_versions = 2 [json_name = "httpVersions"];</code>
       */
      public int getHttpVersionsCount() {
        if (httpVersionsBuilder_ == null) {
          return httpVersions_.size();
        } else {
          return httpVersionsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .server.v1.HTTPVersion http_versions = 2 [json_name = "httpVersions"];</code>
       */
      public server.v1.Server.HTTPVersion getHttpVersions(int index) {
        if (httpVersionsBuilder_ == null) {
          return httpVersions_.get(index);
        } else {
          return httpVersionsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .server.v1.HTTPVersion http_versions = 2 [json_name = "httpVersions"];</code>
       */
      public Builder setHttpVersions(
          int index, server.v1.Server.HTTPVersion value) {
        if (httpVersionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHttpVersionsIsMutable();
          httpVersions_.set(index, value);
          onChanged();
        } else {
          httpVersionsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .server.v1.HTTPVersion http_versions = 2 [json_name = "httpVersions"];</code>
       */
      public Builder setHttpVersions(
          int index, server.v1.Server.HTTPVersion.Builder builderForValue) {
        if (httpVersionsBuilder_ == null) {
          ensureHttpVersionsIsMutable();
          httpVersions_.set(index, builderForValue.build());
          onChanged();
        } else {
          httpVersionsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .server.v1.HTTPVersion http_versions = 2 [json_name = "httpVersions"];</code>
       */
      public Builder addHttpVersions(server.v1.Server.HTTPVersion value) {
        if (httpVersionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHttpVersionsIsMutable();
          httpVersions_.add(value);
          onChanged();
        } else {
          httpVersionsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .server.v1.HTTPVersion http_versions = 2 [json_name = "httpVersions"];</code>
       */
      public Builder addHttpVersions(
          int index, server.v1.Server.HTTPVersion value) {
        if (httpVersionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHttpVersionsIsMutable();
          httpVersions_.add(index, value);
          onChanged();
        } else {
          httpVersionsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .server.v1.HTTPVersion http_versions = 2 [json_name = "httpVersions"];</code>
       */
      public Builder addHttpVersions(
          server.v1.Server.HTTPVersion.Builder builderForValue) {
        if (httpVersionsBuilder_ == null) {
          ensureHttpVersionsIsMutable();
          httpVersions_.add(builderForValue.build());
          onChanged();
        } else {
          httpVersionsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .server.v1.HTTPVersion http_versions = 2 [json_name = "httpVersions"];</code>
       */
      public Builder addHttpVersions(
          int index, server.v1.Server.HTTPVersion.Builder builderForValue) {
        if (httpVersionsBuilder_ == null) {
          ensureHttpVersionsIsMutable();
          httpVersions_.add(index, builderForValue.build());
          onChanged();
        } else {
          httpVersionsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .server.v1.HTTPVersion http_versions = 2 [json_name = "httpVersions"];</code>
       */
      public Builder addAllHttpVersions(
          java.lang.Iterable<? extends server.v1.Server.HTTPVersion> values) {
        if (httpVersionsBuilder_ == null) {
          ensureHttpVersionsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, httpVersions_);
          onChanged();
        } else {
          httpVersionsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .server.v1.HTTPVersion http_versions = 2 [json_name = "httpVersions"];</code>
       */
      public Builder clearHttpVersions() {
        if (httpVersionsBuilder_ == null) {
          httpVersions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          httpVersionsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .server.v1.HTTPVersion http_versions = 2 [json_name = "httpVersions"];</code>
       */
      public Builder removeHttpVersions(int index) {
        if (httpVersionsBuilder_ == null) {
          ensureHttpVersionsIsMutable();
          httpVersions_.remove(index);
          onChanged();
        } else {
          httpVersionsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .server.v1.HTTPVersion http_versions = 2 [json_name = "httpVersions"];</code>
       */
      public server.v1.Server.HTTPVersion.Builder getHttpVersionsBuilder(
          int index) {
        return getHttpVersionsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .server.v1.HTTPVersion http_versions = 2 [json_name = "httpVersions"];</code>
       */
      public server.v1.Server.HTTPVersionOrBuilder getHttpVersionsOrBuilder(
          int index) {
        if (httpVersionsBuilder_ == null) {
          return httpVersions_.get(index);  } else {
          return httpVersionsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .server.v1.HTTPVersion http_versions = 2 [json_name = "httpVersions"];</code>
       */
      public java.util.List<? extends server.v1.Server.HTTPVersionOrBuilder> 
           getHttpVersionsOrBuilderList() {
        if (httpVersionsBuilder_ != null) {
          return httpVersionsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(httpVersions_);
        }
      }
      /**
       * <code>repeated .server.v1.HTTPVersion http_versions = 2 [json_name = "httpVersions"];</code>
       */
      public server.v1.Server.HTTPVersion.Builder addHttpVersionsBuilder() {
        return getHttpVersionsFieldBuilder().addBuilder(
            server.v1.Server.HTTPVersion.getDefaultInstance());
      }
      /**
       * <code>repeated .server.v1.HTTPVersion http_versions = 2 [json_name = "httpVersions"];</code>
       */
      public server.v1.Server.HTTPVersion.Builder addHttpVersionsBuilder(
          int index) {
        return getHttpVersionsFieldBuilder().addBuilder(
            index, server.v1.Server.HTTPVersion.getDefaultInstance());
      }
      /**
       * <code>repeated .server.v1.HTTPVersion http_versions = 2 [json_name = "httpVersions"];</code>
       */
      public java.util.List<server.v1.Server.HTTPVersion.Builder> 
           getHttpVersionsBuilderList() {
        return getHttpVersionsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          server.v1.Server.HTTPVersion, server.v1.Server.HTTPVersion.Builder, server.v1.Server.HTTPVersionOrBuilder> 
          getHttpVersionsFieldBuilder() {
        if (httpVersionsBuilder_ == null) {
          httpVersionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              server.v1.Server.HTTPVersion, server.v1.Server.HTTPVersion.Builder, server.v1.Server.HTTPVersionOrBuilder>(
                  httpVersions_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          httpVersions_ = null;
        }
        return httpVersionsBuilder_;
      }

      private java.lang.Object port_ = "";
      /**
       * <code>string port = 3 [json_name = "port"];</code>
       * @return The port.
       */
      public java.lang.String getPort() {
        java.lang.Object ref = port_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          port_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string port = 3 [json_name = "port"];</code>
       * @return The bytes for port.
       */
      public com.google.protobuf.ByteString
          getPortBytes() {
        java.lang.Object ref = port_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          port_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string port = 3 [json_name = "port"];</code>
       * @param value The port to set.
       * @return This builder for chaining.
       */
      public Builder setPort(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string port = 3 [json_name = "port"];</code>
       * @return This builder for chaining.
       */
      public Builder clearPort() {
        
        port_ = getDefaultInstance().getPort();
        onChanged();
        return this;
      }
      /**
       * <code>string port = 3 [json_name = "port"];</code>
       * @param value The bytes for port to set.
       * @return This builder for chaining.
       */
      public Builder setPortBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        port_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:server.v1.ProtocolSupport)
    }

    // @@protoc_insertion_point(class_scope:server.v1.ProtocolSupport)
    private static final server.v1.Server.ProtocolSupport DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new server.v1.Server.ProtocolSupport();
    }

    public static server.v1.Server.ProtocolSupport getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProtocolSupport>
        PARSER = new com.google.protobuf.AbstractParser<ProtocolSupport>() {
      @java.lang.Override
      public ProtocolSupport parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProtocolSupport(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProtocolSupport> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProtocolSupport> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public server.v1.Server.ProtocolSupport getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HTTPVersionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:server.v1.HTTPVersion)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 major = 1 [json_name = "major"];</code>
     * @return The major.
     */
    int getMajor();

    /**
     * <code>int32 minor = 2 [json_name = "minor"];</code>
     * @return The minor.
     */
    int getMinor();
  }
  /**
   * Protobuf type {@code server.v1.HTTPVersion}
   */
  public static final class HTTPVersion extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:server.v1.HTTPVersion)
      HTTPVersionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HTTPVersion.newBuilder() to construct.
    private HTTPVersion(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HTTPVersion() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new HTTPVersion();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HTTPVersion(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              major_ = input.readInt32();
              break;
            }
            case 16: {

              minor_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return server.v1.Server.internal_static_server_v1_HTTPVersion_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return server.v1.Server.internal_static_server_v1_HTTPVersion_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              server.v1.Server.HTTPVersion.class, server.v1.Server.HTTPVersion.Builder.class);
    }

    public static final int MAJOR_FIELD_NUMBER = 1;
    private int major_;
    /**
     * <code>int32 major = 1 [json_name = "major"];</code>
     * @return The major.
     */
    @java.lang.Override
    public int getMajor() {
      return major_;
    }

    public static final int MINOR_FIELD_NUMBER = 2;
    private int minor_;
    /**
     * <code>int32 minor = 2 [json_name = "minor"];</code>
     * @return The minor.
     */
    @java.lang.Override
    public int getMinor() {
      return minor_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (major_ != 0) {
        output.writeInt32(1, major_);
      }
      if (minor_ != 0) {
        output.writeInt32(2, minor_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (major_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, major_);
      }
      if (minor_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, minor_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof server.v1.Server.HTTPVersion)) {
        return super.equals(obj);
      }
      server.v1.Server.HTTPVersion other = (server.v1.Server.HTTPVersion) obj;

      if (getMajor()
          != other.getMajor()) return false;
      if (getMinor()
          != other.getMinor()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MAJOR_FIELD_NUMBER;
      hash = (53 * hash) + getMajor();
      hash = (37 * hash) + MINOR_FIELD_NUMBER;
      hash = (53 * hash) + getMinor();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static server.v1.Server.HTTPVersion parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static server.v1.Server.HTTPVersion parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static server.v1.Server.HTTPVersion parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static server.v1.Server.HTTPVersion parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static server.v1.Server.HTTPVersion parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static server.v1.Server.HTTPVersion parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static server.v1.Server.HTTPVersion parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static server.v1.Server.HTTPVersion parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static server.v1.Server.HTTPVersion parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static server.v1.Server.HTTPVersion parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static server.v1.Server.HTTPVersion parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static server.v1.Server.HTTPVersion parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(server.v1.Server.HTTPVersion prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code server.v1.HTTPVersion}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:server.v1.HTTPVersion)
        server.v1.Server.HTTPVersionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return server.v1.Server.internal_static_server_v1_HTTPVersion_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return server.v1.Server.internal_static_server_v1_HTTPVersion_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                server.v1.Server.HTTPVersion.class, server.v1.Server.HTTPVersion.Builder.class);
      }

      // Construct using server.v1.Server.HTTPVersion.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        major_ = 0;

        minor_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return server.v1.Server.internal_static_server_v1_HTTPVersion_descriptor;
      }

      @java.lang.Override
      public server.v1.Server.HTTPVersion getDefaultInstanceForType() {
        return server.v1.Server.HTTPVersion.getDefaultInstance();
      }

      @java.lang.Override
      public server.v1.Server.HTTPVersion build() {
        server.v1.Server.HTTPVersion result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public server.v1.Server.HTTPVersion buildPartial() {
        server.v1.Server.HTTPVersion result = new server.v1.Server.HTTPVersion(this);
        result.major_ = major_;
        result.minor_ = minor_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof server.v1.Server.HTTPVersion) {
          return mergeFrom((server.v1.Server.HTTPVersion)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(server.v1.Server.HTTPVersion other) {
        if (other == server.v1.Server.HTTPVersion.getDefaultInstance()) return this;
        if (other.getMajor() != 0) {
          setMajor(other.getMajor());
        }
        if (other.getMinor() != 0) {
          setMinor(other.getMinor());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        server.v1.Server.HTTPVersion parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (server.v1.Server.HTTPVersion) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int major_ ;
      /**
       * <code>int32 major = 1 [json_name = "major"];</code>
       * @return The major.
       */
      @java.lang.Override
      public int getMajor() {
        return major_;
      }
      /**
       * <code>int32 major = 1 [json_name = "major"];</code>
       * @param value The major to set.
       * @return This builder for chaining.
       */
      public Builder setMajor(int value) {
        
        major_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 major = 1 [json_name = "major"];</code>
       * @return This builder for chaining.
       */
      public Builder clearMajor() {
        
        major_ = 0;
        onChanged();
        return this;
      }

      private int minor_ ;
      /**
       * <code>int32 minor = 2 [json_name = "minor"];</code>
       * @return The minor.
       */
      @java.lang.Override
      public int getMinor() {
        return minor_;
      }
      /**
       * <code>int32 minor = 2 [json_name = "minor"];</code>
       * @param value The minor to set.
       * @return This builder for chaining.
       */
      public Builder setMinor(int value) {
        
        minor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 minor = 2 [json_name = "minor"];</code>
       * @return This builder for chaining.
       */
      public Builder clearMinor() {
        
        minor_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:server.v1.HTTPVersion)
    }

    // @@protoc_insertion_point(class_scope:server.v1.HTTPVersion)
    private static final server.v1.Server.HTTPVersion DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new server.v1.Server.HTTPVersion();
    }

    public static server.v1.Server.HTTPVersion getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HTTPVersion>
        PARSER = new com.google.protobuf.AbstractParser<HTTPVersion>() {
      @java.lang.Override
      public HTTPVersion parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HTTPVersion(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HTTPVersion> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HTTPVersion> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public server.v1.Server.HTTPVersion getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_server_v1_ServerMetadata_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_server_v1_ServerMetadata_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_server_v1_ProtocolSupport_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_server_v1_ProtocolSupport_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_server_v1_HTTPVersion_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_server_v1_HTTPVersion_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026server/v1/server.proto\022\tserver.v1\"^\n\016S" +
      "erverMetadata\022\022\n\004host\030\001 \001(\tR\004host\0228\n\tpro" +
      "tocols\030\002 \003(\0132\032.server.v1.ProtocolSupport" +
      "R\tprotocols\"\223\001\n\017ProtocolSupport\022/\n\010proto" +
      "col\030\001 \001(\0162\023.server.v1.ProtocolR\010protocol" +
      "\022;\n\rhttp_versions\030\002 \003(\0132\026.server.v1.HTTP" +
      "VersionR\014httpVersions\022\022\n\004port\030\003 \001(\tR\004por" +
      "t\"9\n\013HTTPVersion\022\024\n\005major\030\001 \001(\005R\005major\022\024" +
      "\n\005minor\030\002 \001(\005R\005minor*N\n\010Protocol\022\030\n\024PROT" +
      "OCOL_UNSPECIFIED\020\000\022\021\n\rPROTOCOL_GRPC\020\001\022\025\n" +
      "\021PROTOCOL_GRPC_WEB\020\002b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_server_v1_ServerMetadata_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_server_v1_ServerMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_server_v1_ServerMetadata_descriptor,
        new java.lang.String[] { "Host", "Protocols", });
    internal_static_server_v1_ProtocolSupport_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_server_v1_ProtocolSupport_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_server_v1_ProtocolSupport_descriptor,
        new java.lang.String[] { "Protocol", "HttpVersions", "Port", });
    internal_static_server_v1_HTTPVersion_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_server_v1_HTTPVersion_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_server_v1_HTTPVersion_descriptor,
        new java.lang.String[] { "Major", "Minor", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
